Repository ZhiLinR/SMU-CS203, pull requests merged in 2024-11, with the labels that each got.

#43 Minor README Changes
  .gitignore
  .vscode/settings.json
  README.md
Labels: documentation

#45 aws user task def
  .github/workflows/aws-user.yml
Labels: enhancement

#17 Tournament Admin Microservice
  .github/workflows/pre-commit.yml
  Backend/Tournament_Admin/.idea/.gitignore
  Backend/Tournament_Admin/.idea/Tournament_Admin.iml
  Backend/Tournament_Admin/.idea/compiler.xml
  Backend/Tournament_Admin/.idea/encodings.xml
  Backend/Tournament_Admin/.idea/jarRepositories.xml
  Backend/Tournament_Admin/.idea/misc.xml
  Backend/Tournament_Admin/.idea/modules.xml
  Backend/Tournament_Admin/.idea/vcs.xml
  Backend/Tournament_Admin/README.md
  Backend/Tournament_Admin/TournamentAdminService/.gitignore
  Backend/Tournament_Admin/TournamentAdminService/.mvn/wrapper/maven-wrapper.properties
  Backend/Tournament_Admin/TournamentAdminService/Dockerfile
  Backend/Tournament_Admin/TournamentAdminService/docker-compose.yaml
  Backend/Tournament_Admin/TournamentAdminService/mvnw
  Backend/Tournament_Admin/TournamentAdminService/mvnw.cmd
  Backend/Tournament_Admin/TournamentAdminService/pom.xml
  Backend/Tournament_Admin/TournamentAdminService/src/main/java/TournamentAdminService/TournamentAdminServiceApplication.java
  Backend/Tournament_Admin/TournamentAdminService/src/main/java/TournamentAdminService/config/AppConfig.java
  Backend/Tournament_Admin/TournamentAdminService/src/main/java/TournamentAdminService/config/SecurityConfig.java
  Backend/Tournament_Admin/TournamentAdminService/src/main/java/TournamentAdminService/controller/MatchupController.java
  Backend/Tournament_Admin/TournamentAdminService/src/main/java/TournamentAdminService/controller/TournamentController.java
  Backend/Tournament_Admin/TournamentAdminService/src/main/java/TournamentAdminService/dto/GameResultRequest.java
  Backend/Tournament_Admin/TournamentAdminService/src/main/java/TournamentAdminService/model/Matchup.java
  Backend/Tournament_Admin/TournamentAdminService/src/main/java/TournamentAdminService/model/MatchupId.java
  Backend/Tournament_Admin/TournamentAdminService/src/main/java/TournamentAdminService/model/Tournament.java
  Backend/Tournament_Admin/TournamentAdminService/src/main/java/TournamentAdminService/repository/MatchupRepository.java
  Backend/Tournament_Admin/TournamentAdminService/src/main/java/TournamentAdminService/repository/TournamentRepository.java
  Backend/Tournament_Admin/TournamentAdminService/src/main/java/TournamentAdminService/response/StandardApiResponse.java
  Backend/Tournament_Admin/TournamentAdminService/src/main/java/TournamentAdminService/service/MatchupService.java
  Backend/Tournament_Admin/TournamentAdminService/src/main/java/TournamentAdminService/service/TournamentService.java
  Backend/Tournament_Admin/TournamentAdminService/src/main/resources/application.properties
  Backend/Tournament_Admin/TournamentAdminService/src/test/java/MatchupServiceTest.java
  Backend/Tournament_Admin/TournamentAdminService/src/test/java/TournamentAdminServiceTest.java
  git-hooks/pre-commit/check-gitignore.sh
  git-hooks/pre-commit/check-staged-files.sh
Labels: enhancement

#51 cleaned up extra files + added dockerignore
  .github/workflows/aws-admin.yml
  .pre-commit-config.yaml
  Backend/Tournament_Admin/.idea/.gitignore
  Backend/Tournament_Admin/.idea/Tournament_Admin.iml
  Backend/Tournament_Admin/.idea/compiler.xml
  Backend/Tournament_Admin/.idea/encodings.xml
  Backend/Tournament_Admin/.idea/jarRepositories.xml
  Backend/Tournament_Admin/.idea/misc.xml
  Backend/Tournament_Admin/.idea/modules.xml
  Backend/Tournament_Admin/.idea/vcs.xml
  Backend/Tournament_Admin/TournamentAdminService/.dockerignore
Labels: enhancement

#57 fix: enabled cors
  Backend/Matchmaking/package-lock.json
  Backend/Matchmaking/package.json
  Backend/Tournament_User/app/package-lock.json
  Backend/Tournament_User/app/package.json
  Backend/Tournament_User/app/server.js
Labels: bug

#60 Tournaments/tournament user getPlayerTournamentsByStatus
  Backend/Tournament_User/app/controllers/test/tournamentUserController.test.js
  Backend/Tournament_User/app/controllers/tournamentUserController.js
  Backend/Tournament_User/app/models/test/tournamentModel.test.js
  Backend/Tournament_User/app/models/tournamentModel.js
  Backend/Tournament_User/app/routes/tournamentUserRoutes.js
  Backend/Tournament_User/app/services/tournamentUserService.js
Labels: help wanted
